# Generated by Django 6.0.4 on 2026-05-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('website_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('mobile_number', models.CharField(blank=True, max_length=100)),
                ('mail', models.JSONField(default=list)),
                ('core_service', models.TextField(blank=True)),
                ('target_customer', models.TextField(blank=True)),
                ('probable_pain_point', models.TextField(blank=True)),
                ('outreach_opener', models.TextField(blank=True)),
            ],
        ),
    ]
